#!/usr/bin/python3

import subprocess

fd = subprocess.Popen(args,
                      bufsize=1,
                      universal_newlines=True,
                      stdin=subprocess.DEVNULL,
                      stdout=subprocess.PIPE,
                      stderr=subprocess.PIPE)

while 
